spring.application.name = ponto
server.port = 8090

spring.datasource.url = jdbc:postgresql://localhost:5432/ponto
spring.datasource.username = postgres
spring.datasource.password = root

# When putting the V1, change to "validate"
spring.jpa.hibernate.ddl-auto = none

# Flyway
spring.flyway.enabled = true
spring.flyway.locations = classpath:db/migration                           