spring.application.name=ponto
spring.datasource.url = jdbc:postgresql://localhost:5432/ponto
spring.datasource.username = postgres
spring.datasource.password = root
spring.jpa.hibernate.ddl-auto = update
server.port=8090