-- V1: initial schema of the time tracking API
--
-- Tables and columns follow the JPA entities in domain/model exactly, because
-- the application runs with spring.jpa.hibernate.ddl-auto=validate.
-- Spring maps camelCase fields to snake_case columns (dateTime -> date_time).
--
-- Enum columns are VARCHAR + CHECK (not native PostgreSQL ENUM types):
-- Hibernate stores @Enumerated(EnumType.STRING) as text, and a native ENUM
-- column would reject those inserts. The CHECK values must match the Java enum
-- constants; adding a constant to an enum requires a new migration that
-- recreates the corresponding CHECK constraint.
-- =============================================================================

CREATE TABLE employee (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    registration_number VARCHAR(20)  NOT NULL,
    name                VARCHAR(150) NOT NULL,
    cpf                 VARCHAR(11)  NOT NULL,
    email               VARCHAR(254) NOT NULL,
    role                VARCHAR(100) NOT NULL,
    department          VARCHAR(100) NOT NULL,
    status              VARCHAR(30)  NOT NULL,
    created_at          TIMESTAMP    NOT NULL,
    updated_at          TIMESTAMP    NOT NULL,

    CONSTRAINT uk_employee_registration_number UNIQUE (registration_number),
    CONSTRAINT uk_employee_cpf                 UNIQUE (cpf),
    CONSTRAINT uk_employee_email               UNIQUE (email),
    CONSTRAINT ck_employee_status
        CHECK (status IN ('ACTIVE', 'INACTIVE', 'VACATION', 'LEAVE'))
);

CREATE TABLE work_schedule (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                   VARCHAR(100) NOT NULL,
    start_time             TIME         NOT NULL,
    end_time               TIME         NOT NULL,
    daily_workload_minutes INTEGER      NOT NULL,
    break_minutes          INTEGER      NOT NULL DEFAULT 0,
    active                 BOOLEAN      NOT NULL DEFAULT TRUE,

    CONSTRAINT ck_work_schedule_daily_workload CHECK (daily_workload_minutes > 0),
    CONSTRAINT ck_work_schedule_break_minutes  CHECK (break_minutes >= 0)
);

CREATE TABLE work_schedule_worked_days (
    work_schedule_id BIGINT      NOT NULL,
    day_of_week      VARCHAR(30) NOT NULL,

    CONSTRAINT pk_work_schedule_worked_days PRIMARY KEY (work_schedule_id, day_of_week),
    CONSTRAINT fk_work_schedule_worked_days_work_schedule
        FOREIGN KEY (work_schedule_id) REFERENCES work_schedule (id) ON DELETE CASCADE,
    CONSTRAINT ck_work_schedule_worked_days_day_of_week
        CHECK (day_of_week IN ('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY',
                               'FRIDAY', 'SATURDAY', 'SUNDAY'))
);

CREATE TABLE hour_bank (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    balance_minutes          INTEGER   NOT NULL DEFAULT 0,
    previous_balance_minutes INTEGER   NOT NULL DEFAULT 0,
    period_start             DATE      NOT NULL,
    period_end               DATE      NOT NULL,
    expiration_date          DATE,
    last_updated_at          TIMESTAMP NOT NULL,

    CONSTRAINT ck_hour_bank_period CHECK (period_end >= period_start)
);

CREATE TABLE hour_bank_movement (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hour_bank_id  BIGINT       NOT NULL,
    minutes       INTEGER      NOT NULL,
    movement_date TIMESTAMP    NOT NULL,
    description   VARCHAR(255),
    type          VARCHAR(30)  NOT NULL,

    CONSTRAINT fk_hour_bank_movement_hour_bank
        FOREIGN KEY (hour_bank_id) REFERENCES hour_bank (id),
    CONSTRAINT ck_hour_bank_movement_type
        CHECK (type IN ('OVERTIME_CREDIT', 'ABSENCE_DEBIT', 'LATE_DEBIT',
                        'COMPENSATION', 'EXPIRATION', 'MANUAL_ADJUSTMENT'))
);

CREATE INDEX idx_hour_bank_movement_hour_bank ON hour_bank_movement (hour_bank_id);

CREATE TABLE contract (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id       BIGINT      NOT NULL,
    work_schedule_id  BIGINT      NOT NULL,
    hour_bank_id      BIGINT,
    type              VARCHAR(30) NOT NULL,
    base_salary_cents INTEGER     NOT NULL,
    admission_date    DATE        NOT NULL,
    termination_date  DATE,
    status            VARCHAR(30) NOT NULL,
    created_at        TIMESTAMP   NOT NULL,
    updated_at        TIMESTAMP   NOT NULL,

    CONSTRAINT fk_contract_employee
        FOREIGN KEY (employee_id) REFERENCES employee (id),
    CONSTRAINT fk_contract_work_schedule
        FOREIGN KEY (work_schedule_id) REFERENCES work_schedule (id),
    CONSTRAINT fk_contract_hour_bank
        FOREIGN KEY (hour_bank_id) REFERENCES hour_bank (id),
    CONSTRAINT uk_contract_hour_bank UNIQUE (hour_bank_id),
    CONSTRAINT ck_contract_type
        CHECK (type IN ('CLT', 'PJ', 'INTERNSHIP', 'TEMPORARY')),
    CONSTRAINT ck_contract_status
        CHECK (status IN ('ACTIVE', 'SUSPENDED', 'CLOSED')),
    CONSTRAINT ck_contract_base_salary
        CHECK (base_salary_cents >= 0),
    CONSTRAINT ck_contract_dates
        CHECK (termination_date IS NULL OR termination_date >= admission_date)
);

CREATE INDEX idx_contract_employee      ON contract (employee_id);
CREATE INDEX idx_contract_work_schedule ON contract (work_schedule_id);

CREATE TABLE justification (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id    BIGINT       NOT NULL,
    approver_id    BIGINT,
    start_date     DATE         NOT NULL,
    end_date       DATE         NOT NULL,
    reason         TEXT         NOT NULL,
    type           VARCHAR(30)  NOT NULL,
    status         VARCHAR(30)  NOT NULL,
    requested_at   TIMESTAMP    NOT NULL,
    approved_at    TIMESTAMP,
    attachment_url VARCHAR(500),

    CONSTRAINT fk_justification_employee
        FOREIGN KEY (employee_id) REFERENCES employee (id),
    CONSTRAINT fk_justification_approver
        FOREIGN KEY (approver_id) REFERENCES employee (id),
    CONSTRAINT ck_justification_type
        CHECK (type IN ('MEDICAL_CERTIFICATE', 'JUSTIFIED_ABSENCE', 'VACATION',
                        'LEAVE', 'MANUAL_ADJUSTMENT', 'OTHER')),
    CONSTRAINT ck_justification_status
        CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED')),
    CONSTRAINT ck_justification_dates
        CHECK (end_date >= start_date)
);

CREATE INDEX idx_justification_employee ON justification (employee_id);
CREATE INDEX idx_justification_approver ON justification (approver_id);

CREATE TABLE time_record (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contract_id      BIGINT       NOT NULL,
    justification_id BIGINT,
    date_time        TIMESTAMP    NOT NULL,
    type             VARCHAR(30)  NOT NULL,
    origin           VARCHAR(30)  NOT NULL,
    notes            VARCHAR(255),
    created_at       TIMESTAMP    NOT NULL,

    CONSTRAINT fk_time_record_contract
        FOREIGN KEY (contract_id) REFERENCES contract (id),
    CONSTRAINT fk_time_record_justification
        FOREIGN KEY (justification_id) REFERENCES justification (id),
    CONSTRAINT ck_time_record_type
        CHECK (type IN ('CLOCK_IN', 'LUNCH_OUT', 'LUNCH_IN', 'CLOCK_OUT')),
    CONSTRAINT ck_time_record_origin
        CHECK (origin IN ('WEB', 'APP', 'MANUAL'))
);

CREATE INDEX idx_time_record_contract_date_time ON time_record (contract_id, date_time);
CREATE INDEX idx_time_record_justification      ON time_record (justification_id);